import random
import json
from datetime import datetime
from forge_engine import run_agent_proposal

# ANSI Colors for professional look
class Colors:
    HEADER = '\033[95m'
    BLUE = '\033[94m'
    CYAN = '\033[96m'
    GREEN = '\033[92m'
    YELLOW = '\033[93m'
    RED = '\033[91m'
    BOLD = '\033[1m'
    UNDERLINE = '\033[4m'
    END = '\033[0m'

print(Colors.HEADER + "\n" + "═"*85)
print(" " * 30 + "🔥 RSI FORGE")
print(" " * 25 + "Collective Recursive Intelligence Platform")
print("═"*85 + Colors.END)

print(Colors.CYAN + "Professional Terminal Interface v0.9" + Colors.END + "\n")

# Configuration
problem = input(Colors.BOLD + "Main Problem / Goal:\n> " + Colors.END).strip() or \
          "How should we evolve RSI Forge itself in the next 30 days so it becomes a true Collective Recursive Intelligence platform..."

recursive_si_mode = input(Colors.BOLD + "Enable Recursive SI Mode? (y/n): " + Colors.END).lower().startswith('y')
num_rounds = int(input(Colors.BOLD + "Number of rounds (4-8 recommended): " + Colors.END) or "6")
num_agents = 4

history = [f"Human (Round 0): {problem}"]

print(Colors.GREEN + f"\n🚀 Starting {num_rounds}-round session in {'Recursive SI Mode' if recursive_si_mode else 'Standard Mode'}...\n" + Colors.END)

for r in range(1, num_rounds + 1):
    print(Colors.BLUE + f"\n{'─'*85}" + Colors.END)
    print(Colors.BOLD + f"ROUND {r} {'🔄 RECURSIVE SI MODE' if recursive_si_mode else ''}".center(85) + Colors.END)
    print(Colors.BLUE + f"{'─'*85}" + Colors.END + "\n")
    
    # Agents
    for i in range(num_agents):
        proposal = run_agent_proposal(problem, history[-1], r, recursive_si_mode)
        print(Colors.CYAN + f"Agent {i}:" + Colors.END)
        print(proposal[:720] + ("..." if len(proposal) > 720 else "") + "\n")
    
    # Human Anchor
    print(Colors.YELLOW + "🧭 HUMAN ANCHOR INPUT (Round " + str(r) + ")" + Colors.END)
    print(Colors.BOLD + "Paste your prompt below and press Enter:" + Colors.END)
    human_input = input("\n> ").strip()
    
    if human_input:
        history.append(f"Human anchor (Round {r}): {human_input}")
        print(Colors.GREEN + "✅ Human anchor successfully recorded\n" + Colors.END)
    else:
        history.append(f"Collective (Round {r}): No input")
        print(Colors.YELLOW + "⚠️ No input provided — using collective synthesis\n" + Colors.END)
    
    # Smart Phase Transition
    if random.random() > 0.42 or any(kw in human_input.lower() for kw in ["reframe", "phase", "dissolve", "emerge", "meta", "anchor"]):
        print(Colors.RED + "🌊 COGNITIVE PHASE TRANSITION DETECTED" + Colors.END)
        print("   Spontaneous abstraction collapse / reframing occurred.\n")

# Final Report
print(Colors.HEADER + "\n" + "═"*85)
print(" " * 32 + "SESSION COMPLETE")
print("═"*85 + Colors.END)

print(Colors.BOLD + "\nFULL SESSION HISTORY:\n" + Colors.END)
for entry in history:
    print(entry + "\n")

# Markdown Export (Beautiful & Professional)
timestamp = datetime.now().strftime('%Y%m%d_%H%M')
md_content = f"""# RSI Forge Session Report

**Date**: {datetime.now().strftime('%B %d, %Y at %H:%M')}
**Mode**: {'Recursive SI Mode' if recursive_si_mode else 'Standard Mode'}
**Problem**: {problem}

## Session History

"""
for entry in history:
    md_content += f"{entry}\n\n"

md_content += "---\n*Generated by RSI Forge Terminal Interface v0.9*"

with open(f"RSI_Forge_Session_{timestamp}.md", "w", encoding="utf-8") as f:
    f.write(md_content)

print(Colors.GREEN + f"\n✅ Professional Markdown report saved as: **RSI_Forge_Session_{timestamp}.md**" + Colors.END)
print(Colors.CYAN + "   Ready to upload to Grokipaedia or share." + Colors.END)

print(Colors.BOLD + "\nRun again anytime with: python rsiforge_terminal.py" + Colors.END)
